version: "3"

services:
  recruiter-dashboard:
    container_name: recruiter-dashboard
    build:
      context: .
      dockerfile: ./apps/recruiter-dashboard/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    external: true