services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app_network:
    name: app_network
    driver: bridge
    external: false